spring.application.name=backend

spring.application.name=marketplace
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=kevin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true